### PR TITLE
Added matrix inverse operation

### PR DESCRIPTION
**Pull request by thomasbbrunner**
See issue #2

### CODE REVIEW

**Comment by thomasbbrunner** [comment]
I messed up in the first commit and can't squash the commits in the web interface. 

The second commit reverses the changes the first one did and adds the proper corrections.

**Review by hofbi — CHANGES_REQUESTED** [review]
@thomasbbrunner Thank you for your contribution. 

Could you just paste the mentioned slide here as I don't have access to the lecture slides anymore. If you check the online available version of the MMK book you will find that the equation should be correct (see chapter 5.2.2 equation 5.5). Could you verify whether the book of the slides contain an error.

https://link.springer.com/content/pdf/10.1007%2F978-3-642-05457-0.pdf

**Comment by thomasbbrunner** [comment]
Thanks for the reply. I checked the slides and they are right and contain the same equations as the book.

In the same page you referenced, you will see that the distance equation there (**equation 5.6**) uses the inverse of the weights matrix. 

While the distance equation in the cheatsheet uses the weight matrix, without the inverse (corresponds to **equation 5.1** in the book). 

The book uses a confusing notation. Iinstead of setting the weights matrix to the inverse of the covariance matrix, it sets the covariance matrix as the weights matrix and then inverts the weight matrix.

**Comment by thomasbbrunner** [comment]
However, if you use the formulas in the cheatsheet, you will not invert the covariance matrix, and will get the wrong result.

Somewhere the covariance matrix has to be inverted, either in the distance formula, or when calculating the weights.

**Comment by hofbi** [comment]
But they write if you use for W in 5.1 the inverse W_k, then you will receive the distance according to 5.6. Equation 5.5 defines W_k, which is correct. With your modifications we would define the inverse of W_k which is not correct.

Maybe to make this more clear you could add equation 5.6 of the book which then shows that the inverse has to be used. But the definition of W_k should stay as is as this is the correct definition.

**Comment by thomasbbrunner** [comment]
I see what you mean. I still find the book's nomenclature a bit confusing, but I agree that we can't change the definition of the covariance matrix.

To summarize:
W_k is the weight matrix, W_{K,k} is the covariance matrix, and W_k = (W_{K,k})^{-1}
Correct?

**Comment by thomasbbrunner** [comment]
My suggestion would be to substitute the definition of the covariance matrix by this:

b3ee91571f3d93a07aa71b22e69ddd9d

**Comment by hofbi** [comment]
No W_k was just short for W_{K,k} what I used in my comments. My suggestion for this PR would be to add equation 5.6 from the book to the cheatsheet as is shows that (W_{K,k})^{-1} has to be used for the Mahalanobis-distance.

**Comment by markuspi** [comment]
Using both equations 5.1 and 5.6 from the book is confusing in my opinion.
In the exercise lesson, the TA used a new Variable name C_k.
Maybe we could use that approach?
grafik

**Comment by thomasbbrunner** [comment]
I agree with @markuspi. It is also redundant having the distance formula twice in the cheat sheet.

**Comment by hofbi** [comment]
Yes this substitution sounds like a good solution. You can either stick to the C_k notation of the exercise or the notation of the book. You should know which one is used more often by students.

**Comment by thomasbbrunner** [comment]
Sorry, only had time to work on this now. Was preparing for the exam. I changed the notation of the Mahalanobis distance. Now it is using the notation used in the tutorial.

**Pull request merged**
